// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/strego.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskState represents the current state of a task
type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_PENDING     TaskState = 1
	TaskState_TASK_STATE_SCHEDULED   TaskState = 2
	TaskState_TASK_STATE_ACTIVE      TaskState = 3
	TaskState_TASK_STATE_COMPLETED   TaskState = 4
	TaskState_TASK_STATE_FAILED      TaskState = 5
	TaskState_TASK_STATE_RETRY       TaskState = 6
	TaskState_TASK_STATE_DEAD        TaskState = 7
	TaskState_TASK_STATE_CANCELLED   TaskState = 8
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_PENDING",
		2: "TASK_STATE_SCHEDULED",
		3: "TASK_STATE_ACTIVE",
		4: "TASK_STATE_COMPLETED",
		5: "TASK_STATE_FAILED",
		6: "TASK_STATE_RETRY",
		7: "TASK_STATE_DEAD",
		8: "TASK_STATE_CANCELLED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_PENDING":     1,
		"TASK_STATE_SCHEDULED":   2,
		"TASK_STATE_ACTIVE":      3,
		"TASK_STATE_COMPLETED":   4,
		"TASK_STATE_FAILED":      5,
		"TASK_STATE_RETRY":       6,
		"TASK_STATE_DEAD":        7,
		"TASK_STATE_CANCELLED":   8,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_strego_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_proto_strego_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_proto_strego_proto_rawDescGZIP(), []int{0}
}

// Task represents a unit of work to be processed
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Options       *TaskOptions           `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	Metadata      *TaskMetadata          `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_strego_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_strego_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_strego_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Task) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetOptions() *TaskOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Task) GetMetadata() *TaskMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// TaskOptions configures how a task should be processed
type TaskOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	MaxRetry      int32                  `protobuf:"varint,2,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	ProcessAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=process_at,json=processAt,proto3" json:"process_at,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	UniqueKey     string                 `protobuf:"bytes,6,opt,name=unique_key,json=uniqueKey,proto3" json:"unique_key,omitempty"`
	UniqueTtl     *durationpb.Duration   `protobuf:"bytes,7,opt,name=unique_ttl,json=uniqueTtl,proto3" json:"unique_ttl,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOptions) Reset() {
	*x = TaskOptions{}
	mi := &file_proto_strego_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOptions) ProtoMessage() {}

func (x *TaskOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_strego_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOptions.ProtoReflect.Descriptor instead.
func (*TaskOptions) Descriptor() ([]byte, []int) {
	return file_proto_strego_proto_rawDescGZIP(), []int{1}
}

func (x *TaskOptions) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *TaskOptions) GetMaxRetry() int32 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

func (x *TaskOptions) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *TaskOptions) GetProcessAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessAt
	}
	return nil
}

func (x *TaskOptions) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskOptions) GetUniqueKey() string {
	if x != nil {
		return x.UniqueKey
	}
	return ""
}

func (x *TaskOptions) GetUniqueTtl() *durationpb.Duration {
	if x != nil {
		return x.UniqueTtl
	}
	return nil
}

func (x *TaskOptions) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// TaskMetadata contains runtime information about a task
type TaskMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         TaskState              `protobuf:"varint,1,opt,name=state,proto3,enum=strego.v1.TaskState" json:"state,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	RetryCount    int32                  `protobuf:"varint,5,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	LastError     string                 `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	WorkerId      string                 `protobuf:"bytes,7,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	StreamMsgId   string                 `protobuf:"bytes,9,opt,name=stream_msg_id,json=streamMsgId,proto3" json:"stream_msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMetadata) Reset() {
	*x = TaskMetadata{}
	mi := &file_proto_strego_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMetadata) ProtoMessage() {}

func (x *TaskMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_strego_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMetadata.ProtoReflect.Descriptor instead.
func (*TaskMetadata) Descriptor() ([]byte, []int) {
	return file_proto_strego_proto_rawDescGZIP(), []int{2}
}

func (x *TaskMetadata) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *TaskMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TaskMetadata) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TaskMetadata) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *TaskMetadata) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *TaskMetadata) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *TaskMetadata) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskMetadata) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TaskMetadata) GetStreamMsgId() string {
	if x != nil {
		return x.StreamMsgId
	}
	return ""
}

// TaskResult stores the outcome of task processing
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Result        []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_strego_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_strego_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_strego_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *TaskResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// TaskInfo is returned after enqueuing a task
type TaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	State         TaskState              `protobuf:"varint,3,opt,name=state,proto3,enum=strego.v1.TaskState" json:"state,omitempty"`
	ProcessAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=process_at,json=processAt,proto3" json:"process_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_proto_strego_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_strego_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_proto_strego_proto_rawDescGZIP(), []int{4}
}

func (x *TaskInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskInfo) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *TaskInfo) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *TaskInfo) GetProcessAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessAt
	}
	return nil
}

// QueueInfo contains statistics about a queue
type QueueInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pending       int64                  `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	Active        int64                  `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Scheduled     int64                  `protobuf:"varint,4,opt,name=scheduled,proto3" json:"scheduled,omitempty"`
	Retry         int64                  `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty"`
	Dead          int64                  `protobuf:"varint,6,opt,name=dead,proto3" json:"dead,omitempty"`
	Completed     int64                  `protobuf:"varint,7,opt,name=completed,proto3" json:"completed,omitempty"`
	Processed     int64                  `protobuf:"varint,8,opt,name=processed,proto3" json:"processed,omitempty"`
	Failed        int64                  `protobuf:"varint,9,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueInfo) Reset() {
	*x = QueueInfo{}
	mi := &file_proto_strego_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueInfo) ProtoMessage() {}

func (x *QueueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_strego_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueInfo.ProtoReflect.Descriptor instead.
func (*QueueInfo) Descriptor() ([]byte, []int) {
	return file_proto_strego_proto_rawDescGZIP(), []int{5}
}

func (x *QueueInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueInfo) GetPending() int64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *QueueInfo) GetActive() int64 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *QueueInfo) GetScheduled() int64 {
	if x != nil {
		return x.Scheduled
	}
	return 0
}

func (x *QueueInfo) GetRetry() int64 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *QueueInfo) GetDead() int64 {
	if x != nil {
		return x.Dead
	}
	return 0
}

func (x *QueueInfo) GetCompleted() int64 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *QueueInfo) GetProcessed() int64 {
	if x != nil {
		return x.Processed
	}
	return 0
}

func (x *QueueInfo) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

// WorkerInfo contains information about a worker
type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Queues        []string               `protobuf:"bytes,4,rep,name=queues,proto3" json:"queues,omitempty"`
	Concurrency   int32                  `protobuf:"varint,5,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Status        TaskState              `protobuf:"varint,7,opt,name=status,proto3,enum=strego.v1.TaskState" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_proto_strego_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_strego_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_proto_strego_proto_rawDescGZIP(), []int{6}
}

func (x *WorkerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkerInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *WorkerInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *WorkerInfo) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *WorkerInfo) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *WorkerInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *WorkerInfo) GetStatus() TaskState {
	if x != nil {
		return x.Status
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

var File_proto_strego_proto protoreflect.FileDescriptor

const file_proto_strego_proto_rawDesc = "" +
	"\n" +
	"\x12proto/strego.proto\x12\tstrego.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xab\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x120\n" +
	"\aoptions\x18\x04 \x01(\v2\x16.strego.v1.TaskOptionsR\aoptions\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.strego.v1.TaskMetadataR\bmetadata\"\x9c\x03\n" +
	"\vTaskOptions\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x1b\n" +
	"\tmax_retry\x18\x02 \x01(\x05R\bmaxRetry\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x129\n" +
	"\n" +
	"process_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tprocessAt\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"unique_key\x18\x06 \x01(\tR\tuniqueKey\x128\n" +
	"\n" +
	"unique_ttl\x18\a \x01(\v2\x19.google.protobuf.DurationR\tuniqueTtl\x12:\n" +
	"\x06labels\x18\b \x03(\v2\".strego.v1.TaskOptions.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x03\n" +
	"\fTaskMetadata\x12*\n" +
	"\x05state\x18\x01 \x01(\x0e2\x14.strego.v1.TaskStateR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1f\n" +
	"\vretry_count\x18\x05 \x01(\x05R\n" +
	"retryCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError\x12\x1b\n" +
	"\tworker_id\x18\a \x01(\tR\bworkerId\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId\x12\"\n" +
	"\rstream_msg_id\x18\t \x01(\tR\vstreamMsgId\"\xe3\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x125\n" +
	"\bduration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\x97\x01\n" +
	"\bTaskInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12*\n" +
	"\x05state\x18\x03 \x01(\x0e2\x14.strego.v1.TaskStateR\x05state\x129\n" +
	"\n" +
	"process_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tprocessAt\"\xed\x01\n" +
	"\tQueueInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\apending\x18\x02 \x01(\x03R\apending\x12\x16\n" +
	"\x06active\x18\x03 \x01(\x03R\x06active\x12\x1c\n" +
	"\tscheduled\x18\x04 \x01(\x03R\tscheduled\x12\x14\n" +
	"\x05retry\x18\x05 \x01(\x03R\x05retry\x12\x12\n" +
	"\x04dead\x18\x06 \x01(\x03R\x04dead\x12\x1c\n" +
	"\tcompleted\x18\a \x01(\x03R\tcompleted\x12\x1c\n" +
	"\tprocessed\x18\b \x01(\x03R\tprocessed\x12\x16\n" +
	"\x06failed\x18\t \x01(\x03R\x06failed\"\xed\x01\n" +
	"\n" +
	"WorkerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06queues\x18\x04 \x03(\tR\x06queues\x12 \n" +
	"\vconcurrency\x18\x05 \x01(\x05R\vconcurrency\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12,\n" +
	"\x06status\x18\a \x01(\x0e2\x14.strego.v1.TaskStateR\x06status*\xe6\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_PENDING\x10\x01\x12\x18\n" +
	"\x14TASK_STATE_SCHEDULED\x10\x02\x12\x15\n" +
	"\x11TASK_STATE_ACTIVE\x10\x03\x12\x18\n" +
	"\x14TASK_STATE_COMPLETED\x10\x04\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x05\x12\x14\n" +
	"\x10TASK_STATE_RETRY\x10\x06\x12\x13\n" +
	"\x0fTASK_STATE_DEAD\x10\a\x12\x18\n" +
	"\x14TASK_STATE_CANCELLED\x10\bB0Z.github.com/erennakbas/strego/internal/proto;pbb\x06proto3"

var (
	file_proto_strego_proto_rawDescOnce sync.Once
	file_proto_strego_proto_rawDescData []byte
)

func file_proto_strego_proto_rawDescGZIP() []byte {
	file_proto_strego_proto_rawDescOnce.Do(func() {
		file_proto_strego_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_strego_proto_rawDesc), len(file_proto_strego_proto_rawDesc)))
	})
	return file_proto_strego_proto_rawDescData
}

var file_proto_strego_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_strego_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_strego_proto_goTypes = []any{
	(TaskState)(0),                // 0: strego.v1.TaskState
	(*Task)(nil),                  // 1: strego.v1.Task
	(*TaskOptions)(nil),           // 2: strego.v1.TaskOptions
	(*TaskMetadata)(nil),          // 3: strego.v1.TaskMetadata
	(*TaskResult)(nil),            // 4: strego.v1.TaskResult
	(*TaskInfo)(nil),              // 5: strego.v1.TaskInfo
	(*QueueInfo)(nil),             // 6: strego.v1.QueueInfo
	(*WorkerInfo)(nil),            // 7: strego.v1.WorkerInfo
	nil,                           // 8: strego.v1.TaskOptions.LabelsEntry
	(*durationpb.Duration)(nil),   // 9: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_proto_strego_proto_depIdxs = []int32{
	2,  // 0: strego.v1.Task.options:type_name -> strego.v1.TaskOptions
	3,  // 1: strego.v1.Task.metadata:type_name -> strego.v1.TaskMetadata
	9,  // 2: strego.v1.TaskOptions.timeout:type_name -> google.protobuf.Duration
	10, // 3: strego.v1.TaskOptions.process_at:type_name -> google.protobuf.Timestamp
	9,  // 4: strego.v1.TaskOptions.unique_ttl:type_name -> google.protobuf.Duration
	8,  // 5: strego.v1.TaskOptions.labels:type_name -> strego.v1.TaskOptions.LabelsEntry
	0,  // 6: strego.v1.TaskMetadata.state:type_name -> strego.v1.TaskState
	10, // 7: strego.v1.TaskMetadata.created_at:type_name -> google.protobuf.Timestamp
	10, // 8: strego.v1.TaskMetadata.started_at:type_name -> google.protobuf.Timestamp
	10, // 9: strego.v1.TaskMetadata.completed_at:type_name -> google.protobuf.Timestamp
	9,  // 10: strego.v1.TaskResult.duration:type_name -> google.protobuf.Duration
	10, // 11: strego.v1.TaskResult.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 12: strego.v1.TaskInfo.state:type_name -> strego.v1.TaskState
	10, // 13: strego.v1.TaskInfo.process_at:type_name -> google.protobuf.Timestamp
	10, // 14: strego.v1.WorkerInfo.started_at:type_name -> google.protobuf.Timestamp
	0,  // 15: strego.v1.WorkerInfo.status:type_name -> strego.v1.TaskState
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_strego_proto_init() }
func file_proto_strego_proto_init() {
	if File_proto_strego_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_strego_proto_rawDesc), len(file_proto_strego_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_strego_proto_goTypes,
		DependencyIndexes: file_proto_strego_proto_depIdxs,
		EnumInfos:         file_proto_strego_proto_enumTypes,
		MessageInfos:      file_proto_strego_proto_msgTypes,
	}.Build()
	File_proto_strego_proto = out.File
	file_proto_strego_proto_goTypes = nil
	file_proto_strego_proto_depIdxs = nil
}
